---
title: "R Notebooks"
author: "Tom Curnock"
date: "June 16, 2018"
output:
  html_document:
    number_sections: yes
    theme: sandstone
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_notebook:
    number_sections: yes
    theme: sandstone
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r global_options, include=FALSE}
# knitr::opts_chunk$set(tidy=TRUE, results='hold', fig.align='center')
```

A notebook is an interactive R Markdown file. The file contains three types of contents:

* An optional YAML header surrounded by `---`
* R code chunks surrounded by ` ``` `
* Text mixed with simple text formatting


```{r, child = "YAML.Rmd"}
```

```{r, child = "Code_chunks.Rmd"}
```






# Text and formatting


## Paragraphs and line breaks
A paragraph is generated by one or more blank lines.

New paragraph!
Not a new paragraph! Or a new line.
But you can add two or more spaces at the end  
of a line to force a new line.

* list

    ```
    test indent
    doulbe test indent
    x <- 2
    ```

sdfsd
```
test
```

